server:
  port: 8090

spring:
  data:
    mongodb:
      username: ocaroot
      password: ocaroot
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
